#!/usr/bin/env python
# vim: ai ts=4 sts=4 et sw=4 coding=utf-8

import django_tables as tables

class HealthUnitsTable(tables.Table):
    pk          = tables.Column(visible=False, sortable=False)
    code        = tables.Column(verbose_name="Code")
    name        = tables.Column(verbose_name="Name")
    hctype      = tables.Column(verbose_name="Type")
    hsd         = tables.Column(verbose_name="HSD")
    reporters   = tables.Column(verbose_name="Reporters")
    last        = tables.Column(verbose_name="Last Report", sortable=False)
    last_pk     = tables.Column(visible=False, sortable=False)
    last_sort   = tables.Column(visible=False)
    last_color  = tables.Column(sortable=False, visible=False)

class HWReportersTable(tables.Table):
    pk      = tables.Column(visible=False, sortable=False)
    alias   = tables.Column(verbose_name="Alias")
    name    = tables.Column(verbose_name="Name")
    hu      = tables.Column(verbose_name="Health Unit")
    hu_pk   = tables.Column(visible=False, sortable=False)
    contact = tables.Column(verbose_name="Contact", sortable=False)

class DiseasesReportTable(tables.Table):
    hu      = tables.Column(verbose_name="Health Unit")
    af_cases    = tables.Column(verbose_name="C")
    af_deaths   = tables.Column(verbose_name="D")
    ab_cases    = tables.Column(verbose_name="C")
    ab_deaths   = tables.Column(verbose_name="D")
    rb_cases    = tables.Column(verbose_name="C")
    rb_deaths   = tables.Column(verbose_name="D")
    ch_cases    = tables.Column(verbose_name="C")
    ch_deaths   = tables.Column(verbose_name="D")
    dy_cases    = tables.Column(verbose_name="C")
    dy_deaths   = tables.Column(verbose_name="D")
    gw_cases    = tables.Column(verbose_name="C")
    gw_deaths   = tables.Column(verbose_name="D")
    ma_cases    = tables.Column(verbose_name="C")
    ma_deaths   = tables.Column(verbose_name="D")
    me_cases    = tables.Column(verbose_name="C")
    me_deaths   = tables.Column(verbose_name="D")
    mg_cases    = tables.Column(verbose_name="C")
    mg_deaths   = tables.Column(verbose_name="D")
    nt_cases    = tables.Column(verbose_name="C")
    nt_deaths   = tables.Column(verbose_name="D")
    pl_cases    = tables.Column(verbose_name="C")
    pl_deaths   = tables.Column(verbose_name="D")
    yf_cases    = tables.Column(verbose_name="C")
    yf_deaths   = tables.Column(verbose_name="D")
    vf_cases    = tables.Column(verbose_name="C")
    vf_deaths   = tables.Column(verbose_name="D")
    ei_cases    = tables.Column(verbose_name="C")
    ei_deaths   = tables.Column(verbose_name="D")
