#!/bin/bash

# Provides:          rapidsms-webserver reloader
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: restarts webserver in uwsgi mode
# Description:       restarts webserver in uwsgi mode
### END INIT INFO

# set -e

NAME="rapidsms-webserver"

do_start() {
    service cherokee start
}

do_stop() {
    service cherokee start
}

do_restart() {
    do_reload
    service cherokee restart
}

do_reload() {
   echo -n "Reloading $NAME... "
   pgrep uwsgi | while read pid;
    do
        kill -9 $pid
    done
    echo "uwsgi killed."
}

case "$1" in
    start)
        do_start
        ;;
    
    stop)
        do_stop
        ;;

    reload)
	    do_restart
        ;;
    
    reload)
	    do_reload
        ;;
    
    *)
        echo "Usage: $ME {start|stop|restart|reload}" >&2
        exit 1
        ;;
esac

exit 0
